### ISSUE TITLE
oslo.config import is broken for newer versions of oslo.config

### ISSUE THREAD

**Issue by enolfc** [IFCA/caso#29]
caso-extract 
Traceback (most recent call last):
  File "/usr/local/bin/caso-extract", line 6, in <module>
    from caso.cmd.extract import main
  File "/usr/local/lib/python2.7/dist-packages/caso/cmd/extract.py", line 19, in <module>
    from oslo.config import cfg
ImportError: No module named oslo.config

pip freeze  | grep oslo.config
oslo.config==3.1.0

**Comment by enolfc** [comment]
It's fixed in code, should be released.
