### ISSUE TITLE
Failure with KeyError on second cASO run

### ISSUE THREAD

**Issue by alvarolopez** [IFCA/caso#66]
### Description

The first time caso runs it seems to work:

    # caso-extract
    2019-09-11 16:30:34.996 11276 INFO caso.extract.manager [-] Extracting records for project 'ccfe'
    2019-09-11 16:30:50.281 11276 INFO caso.extract.manager [-] Extracted 1250 records for project 'ccfe' from 1970-01-01 00:00:00 to 2019-09-11 15:30:34.995996
    2019-09-11 16:30:50.282 11276 INFO caso.extract.manager [-] Extracting records for project 'jintrac'
    2019-09-11 16:30:57.037 11276 INFO caso.extract.manager [-] Extracted 217 records for project 'jintrac' from 1970-01-01 00:00:00 to 2019-09-11 15:30:34.995996
    2019-09-11 16:30:57.038 11276 INFO caso.extract.manager [-] Extracting records for project 'lz'
    2019-09-11 16:31:51.333 11276 INFO caso.extract.manager [-] Extracted 6021 records for project 'lz' from 1970-01-01 00:00:00 to 2019-09-11 15:30:34.995996

But the second time it is executed:
    
    # caso-extract --config-file
    /opt/caso/etc/caso/caso.conf
    2019-09-11 16:46:09.333 11420 INFO caso.extract.manager [-] Extracting records for project 'ccfe' {}
    2019-09-11 16:46:14.449 11420 ERROR caso.extract.manager [-] Cannot extract records for 'ccfe': KeyError: u'02acf02a-b635-4276-8558-c519b9dcf187'
    2019-09-11 16:46:14.449 11420 ERROR caso.extract.manager Traceback (most recent call last):
    2019-09-11 16:46:14.449 11420 ERROR caso.extract.manager   File "/opt/caso/lib/python2.7/site-packages/caso/extract/manager.py", line 104, in _extract
    2019-09-11 16:46:14.449 11420 ERROR caso.extract.manager     extract_to)
    2019-09-11 16:46:14.449 11420 ERROR caso.extract.manager   File "/opt/caso/lib/python2.7/site-packages/caso/extract/nova.py", line 281, in extract_for_project
    2019-09-11 16:46:14.449 11420 ERROR caso.extract.manager     if records[ server.id].status == "completed":
    2019-09-11 16:46:14.449 11420 ERROR caso.extract.manager KeyError: u'02acf02a-b635-4276-8558-c519b9dcf187'
    2019-09-11 16:46:14.449 11420 ERROR caso.extract.manager

**Comment by alvarolopez** [comment]
A clear failure due to not having unit tests :cry:
